version: '3'
services:
  grafana:
    image: grafana/grafana:5.0.0
    #container_name: grafana-server
    ports:
        - "3000:3000"
    deploy:
        replicas: 1
        update_config: 
                parallelism: 2
                delay: 10s
        restart_policy:
                condition: on-failure
    networks:
        - grafana-network
    volumes:
        - /var/lib/grafana:/var/lib/grafana
        #- /etc/grafana:/etc/grafana
    environment:
        - GF_INSTALL_PLUGINS=grafana-clock-panel,alexanderzobnin-zabbix-app,grafana-simple-json-datasource, grafana-piechart-panel, grafana-worldmap-panel, raintank-worldping-app

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  grafana-network:
